import { NgModule} from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserAnimationsModule} from '@angular/platform-browser/animations';
// import { NoopAnimationsModule} from '@angular/platform-browser/animations';
import { MatButtonModule,
         MatAutocompleteModule,
         MatButtonToggleModule,
         MatCardModule,
         MatCheckboxModule,
         MatChipsModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatGridListModule,
         MatIconModule,
         MatInputModule,
         MatListModule,
         MatMenuModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSelectModule,
         MatSidenavModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSnackBarModule,
         MatSortModule,
         MatTableModule,
         MatTabsModule,
         MatToolbarModule,
         MatTooltipModule,
         MatStepperModule
         
        } from '@angular/material';
import {CdkTableModule} from '@angular/cdk/table';
@NgModule({
  imports: [ CommonModule,
             MatButtonModule,
              MatCheckboxModule,
              MatButtonModule,
              MatAutocompleteModule,
              MatButtonToggleModule,
              MatCardModule,
              MatCheckboxModule,
              MatChipsModule,
              MatDatepickerModule,
              MatDialogModule,
              MatExpansionModule,
              MatGridListModule,
              MatIconModule,
              MatInputModule,
              MatListModule,
              MatMenuModule,
              MatNativeDateModule,
              MatPaginatorModule,
              MatProgressBarModule,
              MatProgressSpinnerModule,
              MatRadioModule,
              MatRippleModule,
              MatSelectModule,
              MatSidenavModule,
              MatSliderModule,
              MatSlideToggleModule,
              MatSnackBarModule,
              MatSortModule,
              MatTableModule,
              MatTabsModule,
              MatToolbarModule,
              MatTooltipModule,
              MatStepperModule,
              // BrowserAnimationsModule,
              // CdkTableModule
  ],
  exports:[ MatButtonModule,
            MatCheckboxModule,
            MatButtonModule,
            MatAutocompleteModule,
            MatButtonToggleModule,
            MatCardModule,
            MatCheckboxModule,
            MatChipsModule,
            MatDatepickerModule,
            MatDialogModule,
            MatExpansionModule,
            MatGridListModule,
            MatIconModule,
            MatInputModule,
            MatListModule,
            MatMenuModule,
            MatNativeDateModule,
            MatPaginatorModule,
            MatProgressBarModule,
            MatProgressSpinnerModule,
            MatRadioModule,
            MatRippleModule,
            MatSelectModule,
            MatSidenavModule,
            MatSliderModule,
            MatSlideToggleModule,
            MatSnackBarModule,
            MatSortModule,
            MatTableModule,
            MatTabsModule,
            MatToolbarModule,
            MatTooltipModule,
            MatStepperModule,
            BrowserAnimationsModule,
            CdkTableModule
          ],
  declarations: []
})
export class MaterialModule { }
